package com.arua.mapper;

import com.arua.dao.ItemStockDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ItemStockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Tue Apr 09 09:49:16 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Tue Apr 09 09:49:16 CST 2019
     */
    int insert(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Tue Apr 09 09:49:16 CST 2019
     */
    ItemStockDO selectByPrimaryKey(Integer id);
    ItemStockDO selectByIteamId(Integer itemId);
    int decreaseStock(@Param(value = "itemId") Integer itemId, @Param(value = "amount") Integer amount);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Tue Apr 09 09:49:16 CST 2019
     */
    List<ItemStockDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbggenerated Tue Apr 09 09:49:16 CST 2019
     */
    int updateByPrimaryKey(ItemStockDO record);
}