package com.arua.mapper;

import com.arua.dao.ItemDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Tue Apr 09 09:49:16 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Tue Apr 09 09:49:16 CST 2019
     */
    int insert(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Tue Apr 09 09:49:16 CST 2019
     */
    ItemDO selectByPrimaryKey(Integer itemId);
    List<ItemDO> listItem();
    void updateBySales(@Param(value = "itemId") Integer itemId, @Param(value = "amount") Integer amount);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Tue Apr 09 09:49:16 CST 2019
     */
    List<ItemDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbggenerated Tue Apr 09 09:49:16 CST 2019
     */
    int updateByPrimaryKey(ItemDO record);
}