package com.arua.mapper;

import com.arua.dao.SequenceDO;
import java.util.List;

public interface SequenceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbggenerated Tue Apr 09 09:49:16 CST 2019
     */
    int insert(SequenceDO record);
    SequenceDO getSequenceByName(String s);
    void updateByPrimaryKey(SequenceDO sequenceDO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbggenerated Tue Apr 09 09:49:16 CST 2019
     */
    List<SequenceDO> selectAll();
}