package com.arua.mapper;

import com.arua.dao.UserDO;
import java.util.List;

public interface UserDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_into
     *
     * @mbggenerated Tue Apr 09 10:50:35 CST 2019
     */
    int deleteByPrimaryKey(Integer id);
    UserDO selectByTelphone(String telphone);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_into
     *
     * @mbggenerated Tue Apr 09 10:50:35 CST 2019
     */
    int insert(UserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_into
     *
     * @mbggenerated Tue Apr 09 10:50:35 CST 2019
     */
    UserDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_into
     *
     * @mbggenerated Tue Apr 09 10:50:35 CST 2019
     */
    List<UserDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_into
     *
     * @mbggenerated Tue Apr 09 10:50:35 CST 2019
     */
    int updateByPrimaryKey(UserDO record);
}