package com.arua.mapper;

import com.arua.dao.UserPasswordDO;
import java.util.List;

public interface UserPasswordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbggenerated Tue Apr 09 11:36:06 CST 2019
     */
    int deleteByPrimaryKey(Integer id);
    UserPasswordDO selectByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbggenerated Tue Apr 09 11:36:06 CST 2019
     */
    int insert(UserPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbggenerated Tue Apr 09 11:36:06 CST 2019
     */
    UserPasswordDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbggenerated Tue Apr 09 11:36:06 CST 2019
     */
    List<UserPasswordDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbggenerated Tue Apr 09 11:36:06 CST 2019
     */
    int updateByPrimaryKey(UserPasswordDO record);
}