package com.arua.dao;

public class UserDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_into.id
     *
     * @mbggenerated Tue Apr 09 10:50:35 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_into.name
     *
     * @mbggenerated Tue Apr 09 10:50:35 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_into.gender
     *
     * @mbggenerated Tue Apr 09 10:50:35 CST 2019
     */
    private Byte gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_into.age
     *
     * @mbggenerated Tue Apr 09 10:50:35 CST 2019
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_into.telphone
     *
     * @mbggenerated Tue Apr 09 10:50:35 CST 2019
     */
    private String telphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_into.register_mode
     *
     * @mbggenerated Tue Apr 09 10:50:35 CST 2019
     */
    private String registerMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_into.thrid_party_id
     *
     * @mbggenerated Tue Apr 09 10:50:35 CST 2019
     */
    private String thridPartyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_into.id
     *
     * @return the value of user_into.id
     *
     * @mbggenerated Tue Apr 09 10:50:35 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_into.id
     *
     * @param id the value for user_into.id
     *
     * @mbggenerated Tue Apr 09 10:50:35 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_into.name
     *
     * @return the value of user_into.name
     *
     * @mbggenerated Tue Apr 09 10:50:35 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_into.name
     *
     * @param name the value for user_into.name
     *
     * @mbggenerated Tue Apr 09 10:50:35 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_into.gender
     *
     * @return the value of user_into.gender
     *
     * @mbggenerated Tue Apr 09 10:50:35 CST 2019
     */
    public Byte getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_into.gender
     *
     * @param gender the value for user_into.gender
     *
     * @mbggenerated Tue Apr 09 10:50:35 CST 2019
     */
    public void setGender(Byte gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_into.age
     *
     * @return the value of user_into.age
     *
     * @mbggenerated Tue Apr 09 10:50:35 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_into.age
     *
     * @param age the value for user_into.age
     *
     * @mbggenerated Tue Apr 09 10:50:35 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_into.telphone
     *
     * @return the value of user_into.telphone
     *
     * @mbggenerated Tue Apr 09 10:50:35 CST 2019
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_into.telphone
     *
     * @param telphone the value for user_into.telphone
     *
     * @mbggenerated Tue Apr 09 10:50:35 CST 2019
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_into.register_mode
     *
     * @return the value of user_into.register_mode
     *
     * @mbggenerated Tue Apr 09 10:50:35 CST 2019
     */
    public String getRegisterMode() {
        return registerMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_into.register_mode
     *
     * @param registerMode the value for user_into.register_mode
     *
     * @mbggenerated Tue Apr 09 10:50:35 CST 2019
     */
    public void setRegisterMode(String registerMode) {
        this.registerMode = registerMode == null ? null : registerMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_into.thrid_party_id
     *
     * @return the value of user_into.thrid_party_id
     *
     * @mbggenerated Tue Apr 09 10:50:35 CST 2019
     */
    public String getThridPartyId() {
        return thridPartyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_into.thrid_party_id
     *
     * @param thridPartyId the value for user_into.thrid_party_id
     *
     * @mbggenerated Tue Apr 09 10:50:35 CST 2019
     */
    public void setThridPartyId(String thridPartyId) {
        this.thridPartyId = thridPartyId == null ? null : thridPartyId.trim();
    }
}